nutart/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('nutcms.urls')),
]

nutcms/urls.py
from django.conf.urls import url, include

from .shortcuts import get_all_posttypes, get_all_taxonomies
from . import views

posttype_pattern = r'^(?P<posttype_slug>' + '|'.join([__.slug for __ in get_all_posttypes()]) +')/'
taxonomy_pattern = r'^(?P<taxonomy_slug>' + '|'.join([__.slug for __ in get_all_taxonomies()]) + ')/'

app_name = 'nutcms'

moviepatterns = [
    url(r'^$', views.MovieView.as_view(), name='movie'),
    url(r'^play/(?:(?P<res_id>[\w-]+)/)?$', views.MoviePlayView.as_view(), name='movieplay'),
    url(r'^download/$', views.MovieDownloadView.as_view(), name='moviedownload'),
]

urlpatterns = [
    # ex: /
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    # ex: /post/ /page/
    url(posttype_pattern + '$', views.EntrytypeView.as_view(), name='posttype'),
    # ex: /movie/fighting-club
    url(r'^(?P<posttype_slug>movie)/' + '(?P<post_slug>[\w-]+)/', include(moviepatterns)),
    # ex: /post/first-news /page/about-us
    url(posttype_pattern + '(?P<post_slug>[\w-]+)/$', views.EntryView.as_view(), name='entry'),
    # ex: /category/ /star/ /director/ /maker/
    url(taxonomy_pattern + '$', views.TaxonomyView.as_view(), name='taxonomy'),
    # ex: /star/will-smith
    url(taxonomy_pattern + '(?P<term_slug>[\w-]+)/$', views.TermView.as_view(), name='term'),
]

nutart/templates/default/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{% block html_language_code %}en{% endblock %}">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="{% block description %}{{ site_options.site_description }}{% endblock %}" />
    <meta name="author" content="{% block author %}author{% endblock %}" />
    <meta name="keywords" content="{% block keywords %}keywords{% endblock %}" />

    <link rel="icon" sizes="192x192" href="{% block icon %}{% endblock %}" />

    <title>{% block title %}{{ site_options.site_name|title }}{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">-->
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static site_options.theme|add:'/static/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static site_options.theme|add:'/static/css/font-awesome/css/font-awesome.min.css' %}">
    {% block before_style %}{% endblock %}
    <link rel="stylesheet" href="{% static site_options.theme|add:'/static/css/style.css' %}" />
    {% block custom_css %}
    {% endblock custom_css %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head_extra %}{% endblock %}
</head>

<body id="{% block body_id %}nutart{% endblock %}" class="{% block body_class %}{% endblock %}">

    {% block header %}
    <div id="header">
        <div class="container-fluid" id="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        header top
                    </div>
                    <div class="col-sm-3">
                        <ul class='nav navbar-nav'>
                            <li>
                                <a href="{% url 'nutcms:login' %}">Login</a>
                            </li>
                            <li>
                                <a href="{% url 'nutcms:register' %}">Register</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid" id="header-mid">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <h1><a href="{% url 'nutcms:index' %}">{{ site_options.site_name|title }}</a></h1>
                    </div>
                    <div class="col-sm-9 hidden-xs">
                        ad here
                    </div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-default container-fluid" id="header-bottom" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle pull-left" data-toggle="collapse" data-target="#navbar-header-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-search pull-right">
                        <form role="search" method="get" class="search-form" action="<?php echo esc_url( home_url( '/' ) ); ?>">
                            <input type="search" class="search-field" placeholder="Search Movies..." value name="s" title="Search for">
                            <button type="submit" class="btn"><i class="fa fa-search" aria-hidden="true"></i></button>
                        </form>
                    </div>
                </div>

                <div class="collapse navbar-collapse" id="navbar-header-collapse">
                    <ul class="nav navbar-nav">
                        {% block navbar_header_collapse %}
                        <li>
                            <a href="#">About</a>
                        </li>
                        <li>
                            <a href="#">Services</a>
                        </li>
                        <li>
                            <a href="#">Contact</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                        {% endblock navbar_header_collapse %}
                    </ul>

                </div>
            </nav>
        </div>
    </div>
    {% endblock header %}

    {% block main_before %}{% endblock main_before %}

    <!-- Page Content -->
    <div class="container" id="main">

        {% block main_top %}{% endblock main_top %}

        <div class="row">
            <div class="col-md-9 col-sm-12">
                {% block main %}{% endblock main %}
            </div>
            <div class="col-md-3 hidden-sm hidden-xs">
                {% block siderbar %}<p>Sider Bar</p>{% endblock siderbar %}
            </div>
        </div>
        <!-- /.row -->

        {% block main_bottom %}{% endblock main_bottom %}

    </div>
    <!-- /.container -->

    {% block main_after %}{% endblock main_after %}

    <!-- Footer -->
    <div class ="container" id="footer">
        <div id="footer1" class="row">
            <div class="col-xs-12 col-sm-9">
                    <div class="row footer-item feature-list">
                        <div class="col-sm-4"><i class="fa fa-star"></i>All is Free!
                        </div>
                        <div class="col-sm-4"><i class="fa fa-star"></i>Multi Streaming Servers!
                        </div>
                        <div class="col-sm-4"><i class="fa fa-star"></i>Biggest Jav Streaming Engine!
                        </div>
                        <div class="col-sm-4"><i class="fa fa-star"></i>Update Daily!
                        </div>
                        <div class="col-sm-4"><i class="fa fa-star"></i>Featuring Top AV Idols!
                        </div>
                        <div class="col-sm-4"><i class="fa fa-star"></i>Mobile Access Anywhere!
                        </div>
                    </div>
                    <div class="footer-item footer-disclaimer">
                        <p>All clips are collected from outside sources. No videos are hosted on this server. javpin.com is not liable for copyright by any country. The javpin.com Team is gathering and sorting jav movies from other websites every day. It's all here and 100% free porn. Best view with Internet Explorer 7+/FireFox/Google Chrome, Flash Player, 1024x768 dimension.</p>
                    </div>
                    <div class="footer-item follow-list">

                    </div>
                </div>
            <div class="col-sm-3 hidden-xs">
                <div class="footer-item">
                    <!--<img src="https://chart.googleapis.com/chart?chs=240x240&chld=L|1&cht=qr&chl=http://javpin.com&choe=UTF-8" alt="QR code for this page" class="qr-code">-->
                </div>
                <div class="footer-item">
                    <p>View this page on your mobile device. Compatible with Android, iOS and others.</p>
                </div>
            </div>
        </div>
        <div id="footer2" class="row">
            <div class="col-lg-12 text-center">
                <ol class="breadcrumb">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ol>
                <small>Copyright since 2016 - Javpin.com - All Rights Reserved.</small>
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.1 -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>-->
    <script src="{% static site_options.theme|add:'/static/js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>-->
    <script src="{% static site_options.theme|add:'/static/js/bootstrap.min.js' %}"></script>

    {% block body_extra %}{% endblock body_extra %}

</body>
</html>

nutart/templates/default/index.html
<!DOCTYPE html>
<html lang="{% block html_language_code %}en{% endblock %}">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="{% block description %}{{ site_options.site_description }}{% endblock %}" />
    <meta name="author" content="{% block author %}author{% endblock %}" />
    <meta name="keywords" content="{% block keywords %}keywords{% endblock %}" />

    <link rel="icon" sizes="192x192" href="{% block icon %}{% endblock %}" />

    <title>{% block title %}{{ site_options.site_name|title }}{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head_extra %}{% endblock %}
</head>

<body id="{% block body_id %}{% endblock %}" class="{% block body_class %}{% endblock %}">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    {% block navbar_collapse %}
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                    {% endblock navbar_collapse %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-md-8 col-sm-12">
                {% block main %}{% endblock main %}
            </div>
            <div class="col-md-4 hidden-sm hidden-xs">
                <p>Sider Bar</p>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <div class ="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                footer
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.1 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
{% block body_extra %}{% endblock body_extra %}
</body>
</html>

nutart/templates/default/movie.html
{% extends site_options.theme|add:"/base.html" %}

{% block title %}{{ movie.title }} | {{ block.super }}{% endblock title %}

{% block before_style %}
<link rel="stylesheet" href="http://vjs.zencdn.net/5.9.2/video-js.css" />
{% endblock before_style %}

{% block main %}
{% block movie_title %}
<div class="row">
    <div class="col-xs-12 entry-title">
        <a href="{{ movie.get_absolute_url }}"><h1>{% block post_title %}{{ movie.title }}{% endblock %}</h1></a>
    </div>
</div>
{% endblock movie_title %}
{% block movie_data %}
<div class="row">
    <div class="col-sm-7 entry-poster">
        <img src="http://pics.dmm.co.jp/mono/movie/adult/rbd634/rbd634pl.jpg" alt="{{ movie.title }}" class="img-thumbnail" />
    </div>
    <div class="col-sm-5 entry-data">
        <!--<dl>
            <dt>ID:&nbsp;</dt>
            <dd>QBD-073</dd>
            <dt>Star(s):&nbsp;</dt>
            <dd itemprop="actors">
                <span itemscope itemtype="http://schema.org/Person">
                    <a itemprop="name" href="">Tsumiki Aina</a>
                </span>
            </dd>
            <dt>Series:&nbsp;</dt>
            <dd>This a very very very very very very long long long long text.</dd>
        </dl>-->
        <table class="table table-striped table-condensed table-bordered">
            <tbody>
                <tr>
                    <th>ID</th>
                    <td>QBD-073</td>
                </tr>
                <tr>
                    <th>Star(s)</th>
                    <td itemprop="actors">
                        <span itemscope itemtype="http://schema.org/Person">
                            <a itemprop="name" href="">Tsumiki Aina</a>
                        </span>
                    </td>
                </tr>
                <tr>
                    <th>Series</th>
                    <td>This a very very very very very very long long long long text.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock movie_data %}
{% block movie_bar %}
<div class="row entry-bar">
    <div class="col-sm-6 entry-like">
        <a href="#" alt="Like It!" title="Like It!">
            <i class="fa fa-heart fa-2x" aria-hidden="true"></i>
        </a>
        <a href="#" alt="Add To My Watch List!" title="Watch Later!">
            <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
        </a>
    </div>
    <div class="col-sm-6 entry-dw">
        <div class="row">
            <div class="col-xs-6">
                <a class="btn center-block" href="{% url 'nutcms:movieplay' posttype_slug='movie' post_slug=view.kwargs.post_slug %}" title="Watch {{ movie.title }} Online!">Watch Online!</a>
            </div>
            <div class="col-xs-6">
                <a class="btn center-block" href="{% url 'nutcms:moviedownload' posttype_slug='movie' post_slug=view.kwargs.post_slug %}" title="Download {{ movie.title }} Now!">Download Now!</a>
            </div>
        </div>
    </div>
</div>
{% endblock movie_bar %}
{% block movie_trailer %}
<div class="row">
    <div class="col-xs-12">
        <h2 class="section-title">Trailer</h2>
    </div>
    <div class="col-xs-12">
        <video class="video-player video-js" poster="http://pics.dmm.co.jp/mono/movie/adult/rbd634/rbd634pl.jpg" data-setup='{"controls": true, "autoplay": false, "preload": "auto", "loop": false}'>
            <source src="http://cc3001.dmm.co.jp/litevideo/freepv/s/shk/shkd00580/shkd00580_sm_w.mp4" type='video/mp4'>
            <source src="http://cc3001.dmm.co.jp/litevideo/freepv/s/shk/shkd00580/shkd00580_sm_w.mp4" type='video/webm'>
            <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a web browser that supports HTML5 video.
            </p>
        </video>
    </div>
</div>
{% endblock movie_trailer %}
{% block movie_description %}
<div class="row">
    <div class="col-xs-12">
        <h2 class="section-title">Description</h2>
    </div>
    <div class="col-xs-12">
        {{ movie.content }}
    </div>
</div>
{% endblock movie_description %}
{% block movie_gallery %}
<div class="row">
    <div class="col-xs-12">
        <h2 class="section-title">Gallery</h2>
    </div>
    <div class="col-xs-12">
        <dl>
            <dt>ID:&nbsp;</dt>
            <dd>{{ view.kwargs.post_slug }}</dd>
            <dt>Star(s):&nbsp;</dt>
            <dd itemprop="actors">
                <span itemscope itemtype="http://schema.org/Person">
                    <a itemprop="name" href="">Tsumiki Aina</a>
                </span>
            </dd>
            <dt>Series:&nbsp;</dt>
            <dd>This a very very very very very very long long long long text.</dd>
        </dl>
    </div>
</div>
{% endblock movie_gallery %}
{% endblock main %}

{% block siderbar %}
<div class="row">
    <div class="col-xs-12 entry-data1">
        <dl class="dl-horizontal">
            <dt>ID:</dt>
            <dd>QBD-073</dd>
            <dt>Star(s):</dt>
            <dd itemprop="actors">
                <span itemscope itemtype="http://schema.org/Person">
                    <a itemprop="name" href="">Tsumiki Aina</a>
                </span>
            </dd>
        </dl>
    </div>
</div>
{% endblock siderbar %}

{% block body_extra %}
<script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
<script src="http://vjs.zencdn.net/5.9.2/video.js"></script>
{% endblock body_extra %}

nutart/templates/default/movieplay.html
{% extends site_options.theme|add:"/base.html" %}

{% block title %}{{ movie.title }} | {{ block.super }}{% endblock title %}

{% block before_style %}
<link rel="stylesheet" href="http://vjs.zencdn.net/5.9.2/video-js.css" />
{% endblock before_style %}

{% block main %}
{% block movie_title %}
<div class="row">
    <div class="col-xs-12 entry-title">
        <a href="{{ movie.get_absolute_url }}"><h1>{% block post_title %}{{ movie.title }}{% endblock %}</h1></a>
    </div>
</div>
{% endblock movie_title %}
{% block movie_player %}
<div class="row">
    <div class="col-xs-12">
        <h2 class="section-title">Server 1</h2>
    </div>
    <div class="col-xs-12">
        <video class="video-player video-js" poster="http://pics.dmm.co.jp/mono/movie/adult/rbd634/rbd634pl.jpg" data-setup='{"controls": true, "autoplay": false, "preload": "auto", "loop": false}'>
            <source src="http://cc3001.dmm.co.jp/litevideo/freepv/s/shk/shkd00580/shkd00580_sm_w.mp4" type='video/mp4'>
            <source src="http://cc3001.dmm.co.jp/litevideo/freepv/s/shk/shkd00580/shkd00580_sm_w.mp4" type='video/webm'>
            <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a web browser that supports HTML5 video.
            </p>
        </video>
    </div>
</div>
{% endblock movie_player %}
{% block movie_bar %}
<div class="row entry-bar">
    <div class="col-sm-6 entry-like">
        <a href="#" alt="Like It!" title="Like It!">
            <i class="fa fa-heart fa-2x" aria-hidden="true"></i>
        </a>
        <a href="#" alt="Add To My Watch List!" title="Watch Later!">
            <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
        </a>
    </div>
    <div class="col-sm-6 entry-dw">
        <div class="row">
            <div class="col-xs-6">
                <a class="btn center-block" href="{% url 'nutcms:movieplay' posttype_slug='movie' post_slug=view.kwargs.post_slug %}" title="Watch {{ movie.title }} Online!">Watch Online!</a>
            </div>
            <div class="col-xs-6">
                <a class="btn center-block" href="{% url 'nutcms:moviedownload' posttype_slug='movie' post_slug=view.kwargs.post_slug %}" title="Download {{ movie.title }} Now!">Download Now!</a>
            </div>
        </div>
    </div>
</div>
{% endblock movie_bar %}
{% block movie_play %}
<div class="row">
    <div class="col-xs-12">
        <h2 class="section-title">Play</h2>
    </div>
    <div class="col-xs-12">
        {{ playlist_html|safe }}
    </div>
</div>
{% endblock movie_play %}

{% endblock main %}

{% block siderbar %}
<div class="row">
    <div class="col-xs-12 entry-data1">
        <dl class="dl-horizontal">
            <dt>ID:</dt>
            <dd>QBD-073</dd>
            <dt>Star(s):</dt>
            <dd itemprop="actors">
                <span itemscope itemtype="http://schema.org/Person">
                    <a itemprop="name" href="">Tsumiki Aina</a>
                </span>
            </dd>
        </dl>
    </div>
</div>
{% endblock siderbar %}

{% block body_extra %}
<script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
<script src="http://vjs.zencdn.net/5.9.2/video.js"></script>
{% endblock body_extra %}

nutart/templates/default/post.html
{% extends site_options.theme|add:"/base.html" %}

{% block title %}{{ post.title }} | {{ block.super }}{% endblock title %}

{% block custom_css %}{% endblock custom_css %}

{% block main %}
<h1>{% block post_title %}{{ post.title }}{% endblock %}</h1>
<p>{% block post_content %}{{ post.content }}{% endblock %}</p>
<ul class="list-unstyled">
    <li>Bootstrap v3.3.6</li>
    <li>jQuery v1.11</li>
</ul>
{% endblock main %}